# With some help from: https://gist.github.com/dgerosa/2e1f47a39180f39bde848e38243efa94

name: build
on: [push]

# Grant the workflow permission to write repository contents so the
# built artifact can be pushed by the GITHUB_TOKEN (github-actions[bot]).
# If your repository uses a protected branch policy that prevents
# workflow pushes, you'll need to relax that or use a PAT stored in
# secrets and pass it to the deploy action instead.
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Build the LaTeX in the `src` directory; FILE is the base name (no .tex)
      DIR: src
      FILE: resume
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Build LaTeX
        uses: dante-ev/latex-action@latest
        with:
          # point to the actual tex file in src
          root_file: resume.tex
          working_directory: ${{ env.DIR }}
      - name: move
        run: mkdir -p github_artifacts && mv ${{ env.DIR }}/${{ env.FILE }}.pdf ./github_artifacts/
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILE }}.pdf
          path: ./github_artifacts
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: github_artifacts
      - name: move
        run: mkdir -p github_deploy && mv github_artifacts/*/* github_deploy
      - name: deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true
          enable_jekyll: true
  copy-index-to-build:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Copy To Branches Action
        uses: planetoftheweb/copy-to-branches@v1.3
        env:
          key: main
          files: index.html CNAME